var hierarchy =
[
    [ "aid::AppConfig", "structaid_1_1AppConfig.html", null ],
    [ "aid::audio::AudioData", "structaid_1_1audio_1_1AudioData.html", null ],
    [ "aid::audio::AudioDecoder", "classaid_1_1audio_1_1AudioDecoder.html", null ],
    [ "aid::core::AudioFingerprintEngine", "classaid_1_1core_1_1AudioFingerprintEngine.html", null ],
    [ "aid::core::FftEngine", "classaid_1_1core_1_1FftEngine.html", null ],
    [ "aid::core::FftEngineConfig", "structaid_1_1core_1_1FftEngineConfig.html", null ],
    [ "aid::core::Fingerprint", "structaid_1_1core_1_1Fingerprint.html", null ],
    [ "aid::core::FingerprintResult", "structaid_1_1core_1_1FingerprintResult.html", null ],
    [ "aid::core::HashGenerator", "classaid_1_1core_1_1HashGenerator.html", null ],
    [ "aid::core::HashGeneratorConfig", "structaid_1_1core_1_1HashGeneratorConfig.html", null ],
    [ "aid::domain::HashLookupResult", "structaid_1_1domain_1_1HashLookupResult.html", null ],
    [ "aid::core::HashMatch", "structaid_1_1core_1_1HashMatch.html", null ],
    [ "aid::server::HttpServer", "classaid_1_1server_1_1HttpServer.html", null ],
    [ "aid::server::HttpServerConfig", "structaid_1_1server_1_1HttpServerConfig.html", null ],
    [ "aid::domain::IndexingResult", "structaid_1_1domain_1_1IndexingResult.html", null ],
    [ "aid::domain::IndexingService", "classaid_1_1domain_1_1IndexingService.html", null ],
    [ "aid::domain::ITrackRepository", "classaid_1_1domain_1_1ITrackRepository.html", [
      [ "aid::storage::SQLiteRepository", "classaid_1_1storage_1_1SQLiteRepository.html", null ]
    ] ],
    [ "aid::domain::MatchingService", "classaid_1_1domain_1_1MatchingService.html", null ],
    [ "aid::domain::MatchOutput", "structaid_1_1domain_1_1MatchOutput.html", null ],
    [ "aid::core::MatchResult", "structaid_1_1core_1_1MatchResult.html", null ],
    [ "aid::core::Peak", "structaid_1_1core_1_1Peak.html", null ],
    [ "aid::core::PeakExtractor", "classaid_1_1core_1_1PeakExtractor.html", null ],
    [ "aid::core::PeakExtractorConfig", "structaid_1_1core_1_1PeakExtractorConfig.html", null ],
    [ "aid::core::Spectrogram", "classaid_1_1core_1_1Spectrogram.html", null ],
    [ "aid::server::Task", "structaid_1_1server_1_1Task.html", null ],
    [ "aid::server::TaskQueue", "classaid_1_1server_1_1TaskQueue.html", null ],
    [ "aid::server::TaskRegistry", "classaid_1_1server_1_1TaskRegistry.html", null ],
    [ "aid::server::TaskState", "structaid_1_1server_1_1TaskState.html", null ],
    [ "aid::domain::TrackInfo", "structaid_1_1domain_1_1TrackInfo.html", null ],
    [ "aid::domain::TrackMetadata", "structaid_1_1domain_1_1TrackMetadata.html", null ],
    [ "aid::core::HashGenerator::UnpackedHash", "structaid_1_1core_1_1HashGenerator_1_1UnpackedHash.html", null ],
    [ "aid::core::VotingEngine", "classaid_1_1core_1_1VotingEngine.html", null ],
    [ "aid::core::VotingEngineConfig", "structaid_1_1core_1_1VotingEngineConfig.html", null ],
    [ "aid::server::WorkerPool", "classaid_1_1server_1_1WorkerPool.html", null ]
];